# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'issue-tracker' do
  
  pod 'FlexLayout', '~>1.3.24'
  pod 'SnapKit', '~>5.6.0'

end
