# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# [Reference] https://cskime.github.io/2022-03-01/podfile

use_frameworks!

def ui_pods
  pod 'FlexLayout', '~>1.3.24'
  pod 'SnapKit', '~>5.6.0'
end

def logic_pods
  pod 'RxSwift', '>=6.5.0'
  pod 'RxRelay', '>=6.5.0'
end

target 'issue-tracker' do
  ui_pods
  logic_pods
  
  target 'issue-trackerUnitTests' do
    inherit! :search_paths
    logic_pods
  end
  
  target 'issue-trackerUITests' do
    inherit! :search_paths
    ui_pods
  end
  
end
