# Uncomment the next line to define a global platform for your project
# [Reference] https://cskime.github.io/2022-03-01/podfile

platform :ios, '14.5'
use_frameworks!

target 'issue-tracker' do
  
  pod 'FlexLayout', '~>1.3.24'
  pod 'SnapKit', '~>5.6.0'
  pod 'RxSwift', '>=6.5.0'
  pod 'RxRelay', '>=6.5.0'
  pod 'RxCocoa', '>=6.5.0'
  pod 'ReactorKit', '3.1.0'
  pod 'FirebaseAuth'
  pod 'FirebaseDynamicLinks'
  
  target 'issue-trackerUnitTests' do
    inherit! :search_paths
  end
  
  target 'issue-trackerUITests' do
    inherit! :complete
  end
  
end
